package com.cps.dbdetails.cpsdetails.util;

public enum SqlUtil {
    PREPID("SELECT cp.name,acquisition.acq_receipt_id,pci.id AS prep_id,pci.last_orchestration_id   AS workflow_id,substr(pci.content_info, instr(pci.content_info, '/', - 1, 1) + 1) AS filename,pci.content_info,pci.modified_date,acquisition.created_date,DELIVERY_FILES.PGUID, DELIVERY_FILES.RESPONSE_CODE, DELIVERY_FILES.RESPONSE_MESSAGE,acquisition_status.acquisition_status,osd.status_desc,repreparewf.count,acquisition.probot_id,delivery_files.delivery_file_name " + "FROM orchestrations ai " + "LEFT JOIN (SELECT preparation_content_id,COUNT(repreparation_workflow) count   FROM orchestrations WHERE repreparation_workflow = 'Y'    \r\n" + "GROUP BY preparation_content_id) repreparewf ON repreparewf.preparation_content_id = ai.preparation_content_id " + "LEFT JOIN contentset_provider        cp ON cp.id = ai.contentset_provider_id " + "LEFT JOIN orchestration_status_def   osd ON osd.id = ai.orchestration_status " + "LEFT JOIN preparation_content_info   pci ON pci.last_orchestration_id = ai.id " + "LEFT JOIN acquisition ON pci.acquisition_receipt_id = acquisition.acq_receipt_id " + "LEFT JOIN acquisition_status ON acquisition.id = acquisition_status.acquisition_id " + "LEFT JOIN orchestration_delivery_info ON pci.last_orchestration_id = orchestration_delivery_info.orchestration_id " + "LEFT JOIN delivery_files ON orchestration_delivery_info.id = delivery_files.orch_delivery_id WHERE pci.id IN "),
    WORKFLOWID("SELECT cp.name,acquisition.acq_receipt_id,pci.id AS prep_id,pci.last_orchestration_id   AS workflow_id,substr(pci.content_info, instr(pci.content_info, '/', - 1, 1) + 1) AS filename,pci.content_info,pci.modified_date,acquisition.created_date,DELIVERY_FILES.PGUID, DELIVERY_FILES.RESPONSE_CODE, DELIVERY_FILES.RESPONSE_MESSAGE,acquisition_status.acquisition_status,osd.status_desc,repreparewf.count,acquisition.probot_id,delivery_files.delivery_file_name " + "FROM orchestrations ai " + "LEFT JOIN (SELECT preparation_content_id,COUNT(repreparation_workflow) count   FROM orchestrations WHERE repreparation_workflow = 'Y'    \r\n" + "GROUP BY preparation_content_id) repreparewf ON repreparewf.preparation_content_id = ai.preparation_content_id " + "LEFT JOIN contentset_provider        cp ON cp.id = ai.contentset_provider_id " + "LEFT JOIN orchestration_status_def   osd ON osd.id = ai.orchestration_status " + "LEFT JOIN preparation_content_info   pci ON pci.last_orchestration_id = ai.id " + "LEFT JOIN acquisition ON pci.acquisition_receipt_id = acquisition.acq_receipt_id " + "LEFT JOIN acquisition_status ON acquisition.id = acquisition_status.acquisition_id " + "LEFT JOIN orchestration_delivery_info ON pci.last_orchestration_id = orchestration_delivery_info.orchestration_id " + "LEFT JOIN delivery_files ON orchestration_delivery_info.id = delivery_files.orch_delivery_id WHERE pci.last_orchestration_id IN "),
    RECEIPTID("SELECT cp.name,acquisition.acq_receipt_id,pci.id AS prep_id,pci.last_orchestration_id   AS workflow_id,substr(pci.content_info, instr(pci.content_info, '/', - 1, 1) + 1) AS filename,pci.content_info,pci.modified_date,acquisition.created_date,DELIVERY_FILES.PGUID, DELIVERY_FILES.RESPONSE_CODE, DELIVERY_FILES.RESPONSE_MESSAGE,acquisition_status.acquisition_status,osd.status_desc,repreparewf.count,acquisition.probot_id,delivery_files.delivery_file_name " + "FROM orchestrations ai " + "LEFT JOIN (SELECT preparation_content_id,COUNT(repreparation_workflow) count   FROM orchestrations WHERE repreparation_workflow = 'Y'    \r\n" + "GROUP BY preparation_content_id) repreparewf ON repreparewf.preparation_content_id = ai.preparation_content_id " + "LEFT JOIN contentset_provider        cp ON cp.id = ai.contentset_provider_id " + "LEFT JOIN orchestration_status_def   osd ON osd.id = ai.orchestration_status " + "LEFT JOIN preparation_content_info   pci ON pci.last_orchestration_id = ai.id " + "LEFT JOIN acquisition ON pci.acquisition_receipt_id = acquisition.acq_receipt_id " + "LEFT JOIN acquisition_status ON acquisition.id = acquisition_status.acquisition_id " + "LEFT JOIN orchestration_delivery_info ON pci.last_orchestration_id = orchestration_delivery_info.orchestration_id " + "LEFT JOIN delivery_files ON orchestration_delivery_info.id = delivery_files.orch_delivery_id WHERE ACQUISITION.ACQ_RECEIPT_ID in "),
    FILENAME("SELECT cp.name,acquisition.acq_receipt_id,pci.id AS prep_id,pci.last_orchestration_id   AS workflow_id,substr(pci.content_info, instr(pci.content_info, '/', - 1, 1) + 1) AS filename,pci.content_info,pci.modified_date,acquisition.created_date,DELIVERY_FILES.PGUID, DELIVERY_FILES.RESPONSE_CODE, DELIVERY_FILES.RESPONSE_MESSAGE,acquisition_status.acquisition_status,osd.status_desc,repreparewf.count,acquisition.probot_id,delivery_files.delivery_file_name " + "FROM orchestrations ai " + "LEFT JOIN (SELECT preparation_content_id,COUNT(repreparation_workflow) count   FROM orchestrations WHERE repreparation_workflow = 'Y'    \r\n" + "GROUP BY preparation_content_id) repreparewf ON repreparewf.preparation_content_id = ai.preparation_content_id " + "LEFT JOIN contentset_provider        cp ON cp.id = ai.contentset_provider_id " + "LEFT JOIN orchestration_status_def   osd ON osd.id = ai.orchestration_status " + "LEFT JOIN preparation_content_info   pci ON pci.last_orchestration_id = ai.id " + "LEFT JOIN acquisition ON pci.acquisition_receipt_id = acquisition.acq_receipt_id " + "LEFT JOIN acquisition_status ON acquisition.id = acquisition_status.acquisition_id " + "LEFT JOIN orchestration_delivery_info ON pci.last_orchestration_id = orchestration_delivery_info.orchestration_id " + "LEFT JOIN delivery_files ON orchestration_delivery_info.id = delivery_files.orch_delivery_id WHERE SUBSTR(PCI.CONTENT_INFO,INSTR(PCI.CONTENT_INFO,'/',-1,1)+1) in "),
    DELIVERYFILENAME("SELECT cp.name,acquisition.acq_receipt_id,pci.id AS prep_id,pci.last_orchestration_id   AS workflow_id,substr(pci.content_info, instr(pci.content_info, '/', - 1, 1) + 1) AS filename,pci.content_info,pci.modified_date,acquisition.created_date,DELIVERY_FILES.PGUID, DELIVERY_FILES.RESPONSE_CODE, DELIVERY_FILES.RESPONSE_MESSAGE,acquisition_status.acquisition_status,osd.status_desc,repreparewf.count,acquisition.probot_id,delivery_files.delivery_file_name " + "FROM orchestrations ai " + "LEFT JOIN (SELECT preparation_content_id,COUNT(repreparation_workflow) count   FROM orchestrations WHERE repreparation_workflow = 'Y'    \r\n" + "GROUP BY preparation_content_id) repreparewf ON repreparewf.preparation_content_id = ai.preparation_content_id " + "LEFT JOIN contentset_provider        cp ON cp.id = ai.contentset_provider_id " + "LEFT JOIN orchestration_status_def   osd ON osd.id = ai.orchestration_status " + "LEFT JOIN preparation_content_info   pci ON pci.last_orchestration_id = ai.id " + "LEFT JOIN acquisition ON pci.acquisition_receipt_id = acquisition.acq_receipt_id " + "LEFT JOIN acquisition_status ON acquisition.id = acquisition_status.acquisition_id " + "LEFT JOIN orchestration_delivery_info ON pci.last_orchestration_id = orchestration_delivery_info.orchestration_id " + "LEFT JOIN delivery_files ON orchestration_delivery_info.id = delivery_files.orch_delivery_id WHERE DELIVERY_FILE_NAME in "),
   BUNDLE_AUDIT("SELECT * FROM cps.BUNDLE_AUDIT_E2E baee WHERE FILENAME  in "),
    ARTICLEID("select * from cps.ARTICLEMETADATA where ARTICLEID in "),
    ARTICLECOUNT("select OUTPUTBUNDLENAME, COUNT(*) FROM CPS.ARTICLEMETADATA WHERE OUTPUTBUNDLENAME in ");
    private final String sql;

    SqlUtil(String sql) {
        this.sql = sql;
    }

    public String getSql() {
        System.out.println("Inside Util");
        return this.sql;
    }
}
